import { AppConfig } from './types';

export const defaultAppConfig: AppConfig = {
  source: {
    url: 'https://github.com/RESukrit/RescuNet',
    type: 'repo',
    lastSynced: new Date().toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }),
  },
  profile: {
    name: 'RescuNet Disaster Management',
    headline: 'Intelligent Disaster Management & Offline Mesh Communication',
    bio: 'P2P mesh routing for SOS distress beacons, dynamic hazard-avoidance routing, and centralized triage command when cellular networks collapse.',
    avatarUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=400&q=80',
    githubUrl: 'https://github.com/RESukrit/RescuNet',
    websiteUrl: 'https://github.com/RESukrit/RescuNet',
    email: 'seksisukrit@gmail.com',
    location: 'Palakkad Sector 4 / Response Zone Alpha',
    statusText: 'Active Mesh Node: BLE & Wi-Fi Direct Relay Online',
  },
  theme: 'slate',
  website: {
    hero: {
      badge: 'Emergency Response & P2P Mesh Protocol',
      title: 'RescuNet: Offline Mesh SOS When Cell Towers Collapse',
      subtitle: 'Routes distress signals phone-to-phone, pushes real-time hazard alerts, and guides survivors along safe evacuation corridors—with zero cellular or internet connection.',
      ctaPrimaryText: 'Launch Command Dashboard',
      ctaPrimaryLink: '#dashboard',
      ctaSecondaryText: 'Open Victim SOS Portal',
      ctaSecondaryLink: '#victim',
    },
    about: {
      summary: 'During severe natural disasters (floods, landslides, earthquakes), cellular infrastructure collapses. RescuNet establishes an offline peer-to-peer (P2P) mesh network using Bluetooth Low Energy (BLE) and Wi-Fi Direct to hop distress packets from device to device until reaching an emergency responder gateway.',
      bullets: [
        'Offline P2P Mesh Network: Multi-hop phone-to-phone broadcast without cell towers or ISP lines',
        'Dynamic Hazard-Avoidance Routing: Automatically bypasses active floodwater, landslide, and fire perimeters',
        'Automated Welfare Tracking & SOS: Timed check-in prompts auto-escalate SOS with GPS and battery telemetry',
        'Central Rescue Command Dashboard: Prioritizes victims by medical urgency and remaining battery life',
      ],
      stats: [
        { label: 'Network Dependency', value: '0% (Offline)' },
        { label: 'Mesh Hop Range', value: '1.2 km/hop' },
        { label: 'Algorithmic Triage', value: 'Automated' },
        { label: 'Low-Power Mode', value: 'Up to 36 hrs' },
      ],
    },
    projects: [
      {
        id: 'proj-rescu-1',
        title: 'Victim SOS Broadcast Portal',
        description: 'Single-touch emergency distress beacon transmitter capturing GPS, remaining battery, and condition with automated mesh packet dispatch.',
        tags: ['HTML5', 'Geolocation API', 'Battery API', 'Emergency UX'],
        stars: 24,
        forks: 6,
        liveUrl: '#victim',
        repoUrl: 'https://github.com/RESukrit/RescuNet/blob/main/templates/victim.html',
        category: 'Client Beacon',
        featured: true,
      },
      {
        id: 'proj-rescu-2',
        title: 'Command Triage & Demographics Dashboard',
        description: 'First responder command map using Leaflet OpenStreetMap with live incident markers, algorithmic priority queue, and dispatch actions.',
        tags: ['Leaflet', 'OpenStreetMap', 'Python Flask', 'Triage Engine'],
        stars: 38,
        forks: 9,
        liveUrl: '#dashboard',
        repoUrl: 'https://github.com/RESukrit/RescuNet/blob/main/templates/dashboard.html',
        category: 'Command & Control',
        featured: true,
      },
      {
        id: 'proj-rescu-3',
        title: 'Offline P2P Multi-Hop Routing Engine',
        description: 'Peer-to-peer packet transmission simulation hopping messages across offline civilian nodes to the nearest active gateway.',
        tags: ['BLE', 'Wi-Fi Direct', 'Mesh Protocols', 'Distributed Systems'],
        stars: 19,
        forks: 4,
        liveUrl: '#mesh',
        repoUrl: 'https://github.com/RESukrit/RescuNet',
        category: 'Networking',
        featured: true,
      },
      {
        id: 'proj-rescu-4',
        title: 'Automated Incident Verification & Pathfinding',
        description: 'Automated telemetry engine verifying citizen hazard reports (blocked roads, rising floodwater) to instantly recalculate safe evacuation routes.',
        tags: ['Automated Telemetry', 'Computer Vision', 'Routing Algorithms'],
        stars: 31,
        forks: 5,
        liveUrl: '#hazards',
        repoUrl: 'https://github.com/RESukrit/RescuNet',
        category: 'Incident Response & Safety',
        featured: false,
      },
    ],
    skills: [
      {
        category: 'Emergency Mesh Protocols',
        items: ['Bluetooth Low Energy (BLE)', 'Wi-Fi Direct P2P', 'Store-and-Forward Routing', 'Zero-Internet Mesh'],
      },
      {
        category: 'Command & Mapping',
        items: ['Leaflet.js', 'OpenStreetMap Tiles', 'Dynamic Polygon Hazards', 'Algorithmic Triage Priority'],
      },
      {
        category: 'Device Hardware Telemetry',
        items: ['HTML5 Geolocation', 'Battery Status API', 'Web Audio Beacons', 'Offline Vector Map Caching'],
      },
      {
        category: 'Backend Architecture',
        items: ['Flask / Express REST API', 'Real-time Signal Dispatch', 'Incident Status State Engine'],
      },
    ],
    highlights: [
      {
        year: '2026',
        title: 'RescuNet Prototype Launch',
        organization: 'Emergency Tech Initiative',
        description: 'Successfully deployed and demonstrated zero-internet mesh SOS transmission and triage dashboard for flood disaster scenarios in Palakkad region.',
      },
      {
        year: '2026',
        title: 'Algorithmic Priority Matrix',
        organization: 'Search & Rescue Systems',
        description: 'Integrated multi-variable triage weighing injury severity, structural collapse, and exponential battery decay factors.',
      },
    ],
    contact: {
      message: 'For emergency coordination, civil defense integration, or repository inquiries, reach out through the official project channels.',
      links: [
        { label: 'GitHub Repository', url: 'https://github.com/RESukrit/RescuNet', icon: 'Github' },
        { label: 'Emergency Operations', url: 'mailto:seksisukrit@gmail.com', icon: 'Mail' },
      ],
    },
  },
  dashboard: {
    kpis: [
      {
        id: 'kpi-1',
        label: 'Active Distress Beacons',
        value: '4',
        change: '+1 past 10m',
        isPositive: false,
        subtext: 'verified triage queue',
        icon: 'AlertTriangle',
      },
      {
        id: 'kpi-2',
        label: 'Critical Priority Score (>50)',
        value: '2',
        change: 'Immediate rescue',
        isPositive: false,
        subtext: 'life-threatening status',
        icon: 'Flame',
      },
      {
        id: 'kpi-3',
        label: 'Responders Deployed',
        value: '5 Teams',
        change: '3 Sectors active',
        isPositive: true,
        subtext: 'NDRF / Civil Defense',
        icon: 'Shield',
      },
      {
        id: 'kpi-4',
        label: 'Battery Depleted (<25%)',
        value: '2 Devices',
        change: 'Critical node decay',
        isPositive: false,
        subtext: 'transmitting low-power beacon',
        icon: 'BatteryLow',
      },
    ],
    trafficData: [
      { date: '11:00 AM', views: 2, uniqueVisitors: 2 },
      { date: '11:10 AM', views: 5, uniqueVisitors: 4 },
      { date: '11:20 AM', views: 9, uniqueVisitors: 7 },
      { date: '11:30 AM', views: 14, uniqueVisitors: 11 },
      { date: '11:40 AM', views: 18, uniqueVisitors: 15 },
    ],
    repoActivityData: [
      { month: 'Sep 11 (09:00)', commits: 4, prs: 1, stars: 5 },
      { month: 'Sep 11 (10:00)', commits: 8, prs: 2, stars: 12 },
      { month: 'Sep 11 (11:00)', commits: 14, prs: 3, stars: 22 },
      { month: 'Sep 11 (12:00)', commits: 19, prs: 4, stars: 38 },
    ],
    trafficSources: [
      { name: 'BLE Mesh Relay', value: 58, color: '#3b82f6' },
      { name: 'Wi-Fi Direct Peer', value: 27, color: '#10b981' },
      { name: 'Gateway Direct', value: 15, color: '#f59e0b' },
    ],
    deployments: [
      {
        id: 'dep-1',
        project: 'RescuNet Flask / Express API',
        environment: 'Disaster Gateway Base',
        status: 'Success',
        branch: 'main',
        commit: 'd461971',
        time: 'Just now',
        url: 'https://github.com/RESukrit/RescuNet',
      },
      {
        id: 'dep-2',
        project: 'Leaflet Command Dashboard',
        environment: 'Emergency Operations Center',
        status: 'Success',
        branch: 'main',
        commit: '054cf2f',
        time: '5 min ago',
        url: 'https://github.com/RESukrit/RescuNet/blob/main/templates/dashboard.html',
      },
      {
        id: 'dep-3',
        project: 'Victim Emergency Web SOS',
        environment: 'Offline P2P Mesh Cache',
        status: 'Success',
        branch: 'main',
        commit: 'b0b69c2',
        time: '12 min ago',
        url: 'https://github.com/RESukrit/RescuNet/blob/main/templates/victim.html',
      },
    ],
    recentActivities: [
      {
        id: 'act-1',
        type: 'deploy',
        title: 'Emergency SOS Broadcast Received',
        description: 'Victim 1 transmitted beacon from 10.053, 76.627 via 3 mesh hops. Priority 74.6 (Trapped under debris).',
        timestamp: '4 minutes ago',
        author: 'Mesh Gateway Alpha',
      },
      {
        id: 'act-2',
        type: 'commit',
        title: 'Flood Hazard Zone Polygon Updated',
        description: 'River overflow boundary extended across Sector 4. Evacuation routes redirected.',
        timestamp: '15 minutes ago',
        author: 'Incident Commander',
      },
      {
        id: 'act-3',
        type: 'star',
        title: 'Rescue Team 2 Dispatched',
        description: 'Inflatable rescue craft mobilized towards Family of 3 (cut off by floodwater).',
        timestamp: '25 minutes ago',
        author: 'Dispatch Center',
      },
    ],
    systemHealth: {
      uptime: '99.98%',
      responseTime: '42ms',
      sslStatus: 'Encrypted Gateway',
      buildStatus: 'Passing (All Tests Green)',
      lighthouseScore: 98,
    },
  },
  rescuNet: {
    activeBeaconCount: 4,
    defaultCoordinates: { lat: 10.053, lng: 76.627 },
    sampleSignals: [
      {
        id: 1,
        name: 'Priya & Child (Node #4)',
        condition: 'Trapped under debris',
        battery: 18,
        lat: 10.0534,
        lng: 76.6272,
        priority: 74.6,
        time: '11:24:10 AM',
        status: 'active',
        notes: 'Collapsed masonry on ground floor. Extraction equipment required.',
        meshHops: 3,
      },
      {
        id: 2,
        name: 'Elderly Resident (Node #7)',
        condition: 'Medical Emergency',
        battery: 34,
        lat: 10.0612,
        lng: 76.6198,
        priority: 59.8,
        time: '11:29:45 AM',
        status: 'active',
        notes: 'Severe respiratory distress. Oxygen cylinder needed.',
        meshHops: 2,
      },
      {
        id: 3,
        name: 'Family of 3 (Node #2)',
        condition: 'Cut off by floodwater',
        battery: 72,
        lat: 10.0451,
        lng: 76.6385,
        priority: 33.4,
        time: '11:32:02 AM',
        status: 'assigned',
        notes: 'Rooftop shelter, water depth 1.8m. Inflatable boat deployed.',
        meshHops: 1,
      },
      {
        id: 4,
        name: 'Forestry Ranger Office',
        condition: 'Trapped in a fire',
        battery: 22,
        lat: 10.0589,
        lng: 76.6341,
        priority: 58.4,
        time: '11:35:18 AM',
        status: 'active',
        notes: 'Brushfire encroaching north fence. Fast evacuation needed.',
        meshHops: 4,
      },
    ],
    hazardZones: [
      {
        id: 'hazard-1',
        title: 'River Basin Flash Flood Zone',
        type: 'flood',
        severity: 'critical',
        center: [10.048, 76.632],
        radius: 650,
        description: 'Active flash flood with strong currents. Avoid Bridge 3 and low-elevation roads.',
        active: true,
      },
      {
        id: 'hazard-2',
        title: 'North Ridge Landslide Hazard',
        type: 'landslide',
        severity: 'high',
        center: [10.065, 76.621],
        radius: 400,
        description: 'Mudslide blocking primary mountain highway. Use East evacuation corridor.',
        active: true,
      },
      {
        id: 'hazard-3',
        title: 'Pine Forest Brushfire',
        type: 'fire',
        severity: 'high',
        center: [10.059, 76.641],
        radius: 500,
        description: 'Fast-moving brushfire spreading southwest. Keep 500m perimeter clear.',
        active: true,
      },
    ],
  },
};
